# Generated by Django 3.0.3 on 2020-08-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate_app.info')),
            ],
        ),
    ]
