# Generated by Django 3.0.3 on 2020-08-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0004_auto_20200812_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
