# Generated by Django 3.0.3 on 2020-08-18 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate_app', '0006_jsoncontent_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonContent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jsonContent',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
