# Generated by Django 3.0.3 on 2020-09-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0007_auto_20200818_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsonContent',
        ),
    ]
